### ISSUE TITLE
Official query syntax for $gt, $gte does not work

### ISSUE THREAD

**Issue by DominikTrenz** [feathersjs-ecosystem/feathers-reactive#62] opened 2017-07-19 00:04 UTC
### Steps to reproduce

I got a feathers-reactive service and i want to query some objects that have dates (named start in the example) that are greater then now:

`this.someService.find({
 query: {
    $sort: {
      start: 1 /* sorting works */
    },
    start: {
      $gte: moment().startOf('day').toDate()  /* this breaks the updates */
    }
  },
  rx: {
    listStrategy: 'always' /* doesn't help */
  }
});
});`

### Expected behavior
I'm expecting updates to my subscription

### Actual behavior
Initial query works, no updates (created ...).
Because of the initial query is working fine and because without the $gt on "start" the updates also work i think the issue is in feathers-reactive

### System configuration

"feathers": "^2.1.3",
"feathers-hooks": "^2.0.1",
"feathers-reactive": "github:feathersjs/feathers-reactive",
"feathers-rest": "^1.7.3",
"feathers-socketio": "^2.0.0",

**Comment by DominikTrenz** [comment] 2017-07-19 01:56
Another strange behaviour:

When i patch one object (object patched is triggered) it triggers an update, but the updates data is empty and the total count is incorrect, but not correct.

Initial query:
{total: 12, limit: 5, skip: 0, data: Array(5)}
Patched one of the object:
{total: 7, limit: 5, skip: 0, data: Array(0)}

**Comment by daffl** [comment] 2017-07-19 02:53
This means you did not set the `idField` property to the correct id.

**Comment by DominikTrenz** [comment] 2017-07-19 12:33
Ok with the idField property the patch works. But create still doesn't trigger

**Comment by DominikTrenz** [comment] 2017-08-02 04:00
It's still not working. Any news on this topic?

**Comment by khwerhahn** [comment] 2017-08-06 17:44
I have exactly the same problem. Creates dont trigger.

**Comment by DominikTrenz** [comment] 2017-08-08 02:12
Some more Information:
The "xyz created" frame arrives at the client. But not the original "find" frame.

**Comment by jobobo21** [comment] 2017-10-17 19:26
I ran in to a similar problem with create events (#73 ). With my scenario the value in the query needs to be the right prop type to be updated on post. I have successfully done a similar gte date query with momentjs ect ` start: { $gte:  moment().startOf('day').format(/* enter format of date here */)}` Hopefully this helps but I did discover that if your value is in the wrong type (string, int, float, date, ect...) the query and most events will work but create will not.

**Comment by DominikTrenz** [comment] 2017-10-18 17:31
Great find @jobobo21 !! Thanks
Indeed the date had to be in this format: 'YYYY-MM-DDTHH:mm:ss[Z]' and not a standard date object.
Strange that every other crud method worked...

**Comment by jobobo21** [comment] 2017-10-18 19:26
Yeah no worries I had to do the debugging also.  I'm glad my monitor couldn't hear all the creative vocabulary I was shouting at it in the process. As stated by @daffl  in #73 it is related to how feathers-reactive doesnt know what variable format the ORM (sequelize, mongoose, waterline, ect ...)  is requiring.

**Comment by daffl** [comment] 2017-10-18 19:47
I wonder if there is a way to prevent/detect this. I'm not seeing how though. If anybody wants to add a note about this to the readme, that would be fantastic though.

**Comment by jobobo21** [comment] 2017-10-18 20:36
Updated README and created PR #75

**Comment by daffl** [comment] 2017-10-27 01:10
Pulled in @jobobo21's update so I think we can close this issue. Thanks for digging into this everybody!

**Closed by daffl** 2017-10-27 01:10 UTC

**Comment by h-nasu** [comment] 2019-03-06 03:08
This is a closed issue, but I just wanted to point out I had difficult time filtering Date Range with nedb. The problem was I was storing Date object inside nedb and when filtering date from Feathers Client it was not working. 
The cause was Feathers converted the Date object to date string before the Find process, when nedb is expecting Date object. So all I have to do was convert the date string to Date object using before hook and filtering worked.
Hope my finding helps people who have similar issue.

**Comment by rayfoss** [comment] 2019-09-05 21:56
@h-nasu I'm really tired of all this inconsistency. I'm going another direction and nuking all date objects all together. Instead using millisecond unix time stamps.

I'll do it via an application before create hook, then enforce it with ajv validation

**Comment by soullivaneuh** [comment] 2019-12-15 20:45
> I'll do it via an application before create hook

@rayfoss Did you find a generic way to solve this issue?

I face the same situation, and i "fixed" it that way:

```typescript
if (params.query && params.query.date.$gte) {
  params.query.date.$gte = new Date(params.query.date.$gte);
}
if (params.query && params.query.date.$lt) {
  params.query.date.$lt = new Date(params.query.date.$lt);
}
```

But i would to not not add a `if` condition on each potential query I'll do on frontend.

**Comment by rayfoss** [comment] 2019-12-17 22:17
@soullivaneuh 

I just nuked all objects (geoLocation, ObjectID and Date)
https://github.com/feathersjs-ecosystem/feathers-hooks-common/issues/527#issuecomment-529681827
