### ISSUE TITLE
Use TC39 proposal for Symbol.observable to turn resources into Observables

### ISSUE THREAD

**Issue by garbles** [feathersjs-ecosystem/feathers-reactive#43] opened 2017-01-24 06:30 UTC
See [this](https://github.com/tc39/proposal-observable#observablefrom) (+ [polyfill](https://github.com/blesh/symbol-observable)).

The idea is that instead of monkey patching resources into Observables, we should just implement `Symbol.observable` on them and create an observable by passing them into `Observable.from`.

For example,
```js
import {Observable} from 'rxjs';
import app from './app'; // some feathers app

const messages = app.service('messages');

const messages$ = Observable.from(messages.find()); // messages.find() has a Symbol.observable member

messages$
  .switchMap(/* whatever */)
  // etc. ...
```

This removes the direct dependency on RxJS and moves toward the proposed standard. See the implementation in [redux](https://github.com/reactjs/redux/blob/e09b2d1ee4bf4be3499f05d87d57c12fa849647f/src/createStore.js#L209-L240).

**Comment by garbles** [comment] 2017-01-24 06:30
@daffl 🎉

**Comment by daffl** [comment] 2017-01-24 17:28
Thank you! This would probably also solve #41. Would be nice to implement it with the next release but I might not get to look into this until after.

**Comment by garbles** [comment] 2017-01-24 18:15
@daffl Might take a look at it too. Will report back 😄

**Comment by garbles** [comment] 2017-01-25 04:32
I'm now certain that this is not necessary at all. Because all of the service methods return a promise, `Observable.from` will convert them into observables for free. There probably isn't even a need for this mixin? The following example works out of the box with vanilla feathers.

```js
const messages$ = Observable.from(messages.find());
```

Going to close this issue for now. 🌶

**Comment by daffl** [comment] 2017-01-25 05:19
That won't return an observable that updates on real-time events though right?

With `feathers-reactive` configured, the methods return more like a fake Promise since you can also do `messages.find().subscribe()` which will return a list that automatically updates according to the real-time events.

**Comment by garbles** [comment] 2017-01-25 18:02
As discussed on Slack, `messages.find()` should return a promise while `Observable.from(messages.find())` would return an endless stream.

**Comment by j2L4e** [comment] 2017-05-13 14:56
I see a problem here:

Attaching [Symbol.observable] to the returned promise would be a regression to #20 as, in Observable terms, Promises are always hot.

**Comment by daffl** [comment] 2018-04-25 17:34
After a little more research (inhttps://github.com/feathersjs-ecosystem/feathers-reactive/tree/symbol-observable-latest), I think we can close this. @j2L4e's implementation of a `.watch` method was the way to go here.

**Closed by daffl** 2018-04-25 17:34 UTC
