### ISSUE TITLE
Using feathers reactive with rxjs 5.5.x breaks angular production builds (build optimizing)

### ISSUE THREAD

**Issue by DominikTrenz** [feathersjs-ecosystem/feathers-reactive#96] opened 2018-02-10 13:25 UTC
I installed the newest version of feathers-reactive and i tried the version from the rxjs5.5 branch.
I got rxjs 5.5.2 installed. When i try a development build in angular (ionic 3 in my case) everything works. When i try a production build it doesn't work with feathers reactive. 

The error happens in "angular-devkit/build-optimizer". If i start a production build without build optimizer it works, too.

The error i'm getting in the production build:

```
Uncaught Error: Cannot find module 'tslib'
    at o (vendor.js:1)
    at vendor.js:1
    at Object.28.../Observable (vendor.js:1)
    at o (vendor.js:1)
    at vendor.js:1
    at Object.37../FromEventObservable (vendor.js:1)
    at o (vendor.js:1)
    at vendor.js:1
    at Object.181../list (vendor.js:1)
    at o (vendor.js:1)
```

@j2L4e Have you tested your branch with build optimizing?

**Comment by j2L4e** [comment] 2018-02-10 16:27
I haven't. I think you should take this one over to the angular folks.

**Comment by DominikTrenz** [comment] 2018-02-10 16:45
I could fix the issue by importing the module like this:

import * as rx from 'feathers-reactive';

and deleting the index.d.ts form the module. I think there is a bug in the d.ts

**Comment by j2L4e** [comment] 2018-02-12 10:00
angular/angular-cli#8442

**Comment by j2L4e** [comment] 2018-02-12 10:33
Could you check if the `rxjs5.5-autoretry` branch works? Works for me :tm:

**Comment by daffl** [comment] 2018-02-14 03:18
Should also be fixed via #95

**Comment by j2L4e** [comment] 2018-02-14 18:25
@DominikTrenz does your problem persist?

**Comment by DominikTrenz** [comment] 2018-02-15 08:59
@j2L4e I haven't tested it yet. I will test it asap

**Comment by j2L4e** [comment] 2018-02-15 11:52
oops. #98 will take care of that, however I don't think it was the original issue.

**Comment by oussamaABID** [comment] 2018-02-19 09:32
problem persist  with v 0.6

**Comment by j2L4e** [comment] 2018-02-19 10:41
Please create a repo that reproduces the issue.

**Comment by oussamaABID** [comment] 2018-02-19 13:59
this is reproduction example https://github.com/oussamaABID/tslibRxFeathers
* `npm install`
* `ng build --prod` or` npm run build`
* `cd dist `
* `http-server`
and the error : https://github.com/oussamaABID/tslibRxFeathers/blob/master/tslibError.PNG

**Comment by j2L4e** [comment] 2018-02-21 11:56
I'm afraid I have absolutely no idea why this happens...

**Comment by j2L4e** [comment] 2018-02-21 12:05
providing feathers through a factory does work for me:

```ts
import { HttpClient } from '@angular/common/http';
import { FeathersModuleOptions } from './feathers.module';
import feathers from '@feathersjs/feathers';
import feathersRestClient from '@feathersjs/rest-client';
import feathersAuthClient from '@feathersjs/authentication-client';
import feathersSocketIOClient from '@feathersjs/socketio-client';
import * as feathersRx from 'feathers-reactive';
import * as socketio from 'socket.io-client';
import { FeathersOptions } from './feathers.tokens';
import { Feathers } from './feathers.service';
import { FactoryProvider } from '@angular/core';

const defaultOptions: Partial<FeathersModuleOptions> = {
  transport: ['polling', 'websocket']
};

export const feathersProvider: FactoryProvider = {
  provide: Feathers,
  useFactory: feathersFactory,
  deps: [HttpClient, FeathersOptions]
};

export function feathersFactory(httpClient: HttpClient, _options: FeathersModuleOptions) {
  const options = Object.assign({}, defaultOptions, _options);

  const io = socketio(options.url, {
    transports: options.transport
  });

  const app = feathers()
    .configure(feathersSocketIOClient(io))
    .configure(feathersRx({ idField: '_id' }))
    // .configure(feathersRestClient('http://localhost:3030').angularHttpClient(httpClient, { HttpHeaders }))
    .configure(feathersAuthClient({ storage: localStorage }));

  window['feathers'] = app;

  return app;
}
```

**Comment by daffl** [comment] 2018-03-03 22:31
Actually, I think this is similar to #101.

**Comment by oussamaABID** [comment] 2018-03-06 10:50
@j2L4e providing feathers through a factory, not solved tslib error for me :(
```js
@Injectable()
export class myService{
 constructor(@Inject('Feathers') feathers: any) {
        this._feathers = feathers; // init client feathersJs
  }
}
```

**Comment by oussamaABID** [comment] 2018-03-06 13:57
@j2L4e thank you it's work 

```js
@Injectable()
export class MyService{
 constructor(@Inject(Feathers) feathers: any) {
        this._feathers = feathers;
  }
}
```

but only with import like `import * as feathersRx from 'feathers-reactive/dist/feathers-reactive.js';`
* angular   5.1.0

```js
 "dependencies": {
    "@feathersjs/client": "3.4.2",
    "@feathersjs/feathers": "3.1.3",
    "feathers-reactive": "0.6.0",
    "rxjs": "5.5.6",
    "socket.io-client": "2.0.4",
      ....
  },
  "devDependencies": {
    "@angular/cli": "1.6.4",
    "typescript": "2.5.3"
    ....
  }
```

**Comment by j2L4e** [comment] 2018-03-07 14:06
So the gist is that importing from `feathers-reactive/lib` works and importing from `feathers-reactive` does not?

**Comment by oussamaABID** [comment] 2018-03-07 14:31
@j2L4e yes

when i use` feathers-reactive`. i ve this error : 


```
ERROR in node_modules/feathers-reactive/index.d.ts(35,16):
error TS2665: Invalid module name in augmentation. Module '@feathersjs/feathers' resolves to an untyped module
```


with `feathers-reactive/lib` it's OK

**Comment by j2L4e** [comment] 2018-03-07 14:33
do you have `@types/feathersjs__feathers` installed?

**Comment by oussamaABID** [comment] 2018-03-07 14:56
no 

![dep](http://nsa39.casimages.com/img/2018/03/07/18030704004149993.png)

**Comment by j2L4e** [comment] 2018-03-07 14:59
That'll fix your problem. Typings have only very recently been released on DefinitelyTyped.

Install `@types/feathersjs__module` for every `@feathersjs/module` you have installed

**Comment by daffl** [comment] 2018-03-07 16:09
We should probably add those as a dependency eh?

**Comment by j2L4e** [comment] 2018-03-07 16:15
Totally

**Comment by arkenstan** [comment] 2018-03-08 14:21
Thanks was looking for the solution for quite a while

**Comment by oussamaABID** [comment] 2018-03-08 20:50
@j2L4e confirm :+1:

**Comment by j2L4e** [comment] 2018-03-29 12:14
Issue seems to be resolved with installing typings.

**Closed by j2L4e** 2018-03-29 12:14 UTC
