### ISSUE TITLE
EventEmitter memory leak detected

### ISSUE THREAD

**Issue by dottodot** [feathersjs-ecosystem/feathers-reactive#88] opened 2018-01-08 09:38 UTC
As reported here https://github.com/feathersjs/client/issues/236

In my Angular app I've started to get the following error in certain circumstances and not sure why.

> feathers.js:2685 (node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit. 

My page has next and prev links that allow me to navigate to the next gallery but after the 11th navigation it gives the error. In my component below I'm just subscribing to the route change to then fetch the next or previous item

```
export class GalleryDetailComponent implements OnInit, OnDestroy {
  gallery$: Observable<any>;
  constructor(private service: ApiService, private route: ActivatedRoute) {
    service.setup('gallery');
  }

  ngOnInit() {
    this.getGallery();
  }

  getGallery() {
    this.gallery$ = this.route.params.pipe(
      switchMap((params: any) => {
        return this.service.get(params['slug']);
      })
    );
  }

  ngOnDestroy() {}
}
```

and this is my feathers service and api service.
```
@Injectable()
export class FeathersService {
  private _feathers: any;
  private _rest: any;
  constructor(public http: HttpClient) {
    this._rest = rest(environment.host);
    this._feathers = feathers();
    this._feathers.configure(
      authentication({
        storageKey: 'auth-token',
        storage: new CookieStorage({
          path: '/',
          expires: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000)
        })
      })
    );
    this._feathers.configure(
      this._rest.angularHttpClient(this.http, { HttpHeaders: HttpHeaders })
    );
    this._feathers.configure(
      feathersRx({
        listStrategy: 'always',
        idField: '_id'
      })
    );
  }

  // expose services
  public service(name: string) {
    return this._feathers.service(name);
  }
}

```

```
@Injectable()
export class ApiService {
  private service: any;
  constructor(private feathers: FeathersService) {}

  setup(endpoint: string) {
    this.service = this.feathers.service(endpoint);
  }

  get(id: number | string, query?: any) {
    return this.service.watch({ strategy: 'always' }).get(id, { query: query });
  }
}
```

**Comment by j2L4e** [comment] 2018-01-08 09:43
Is the smart strategy leaking as well?

**Comment by dottodot** [comment] 2018-01-08 09:57
Yes just tried with the strategy set to `smart` and the same thing happens.

**Comment by j2L4e** [comment] 2018-01-08 10:02
could be related to #77. Unfortunately I don't have the time to look into this right now. Can you try the rxjs5.5 branch of feathers-reactive?

npm install "https://github.com/feathersjs-ecosystem/feathers-reactive.git#rxjs5.5"

**Comment by dottodot** [comment] 2018-01-08 10:45
Unfortunately that version throws up a load of errors

```
Module not found: Error: Can't resolve 'feathers-reactive' in '/src/client/app/shared/services'
resolve 'feathers-reactive' in '/src/client/app/shared/services'
  Parsed request is a module
  using description file: /package.json (relative path: ./src/client/app/shared/services)
```

**Comment by oussamaABID** [comment] 2018-01-17 16:01
try implement ngDestroy 

```js
  ngOnInit {
      this.gallery$ = this.galleryService.observableGallery$(galleryId);
      this.subscription = this.gallery$.subscribe(gallery => {
         //  your gallery notify code
      });
  }
  ngOnDestroy() {
    this.subscription.unsubscribe();
    this.subscription = null;
    this.gallery$ = null;
  }
```

**Comment by dottodot** [comment] 2018-01-17 16:10
I actually already have unsubscription in place by using ng2-rx-componentdestroyed

which looks like 
```
 getGallery() {
    this.gallery$ = this.route.params.pipe(
      takeUntil(componentDestroyed(this)),
      switchMap((params: any) => {
        return this.service.get(params['slug']);
      })
    );
  }
```
However I don't think that it issue as `ngOnDestroy` isn't called as the component isn't changing I'm just listening to the route changing to load the next item.

**Comment by j2L4e** [comment] 2018-01-17 16:14
Since feathers-reactive is pinned to rxjs 5.4 right now due to #77, I'm pretty sure that the issue is related.

**Comment by oussamaABID** [comment] 2018-01-17 18:13
if you try : 
```js
return this.service..get(id, { query: query }); // in your service no watch
```
and suscribe 
```js
 private subscriptionToUrlParam(): void {
    this.subscriptionUrl = this._route.params.subscribe(params => {
    const yourParams  = this.factoryQuery(params )// adapte your query
    this.gallery =  this.service('gallery').get(yourId, yourParams );
    });
  }
```
the warning persists?

> of corse destroy  this.subscriptionUrl in destory function

**Comment by daffl** [comment] 2018-04-25 17:30
This should be fixed in the latest version.

**Comment by j2L4e** [comment] 2018-07-03 14:02
it is not.

from the rxjs docs:

```
(fromEvent)
 * Every time resulting Observable is subscribed, event handler function will be registered
 * to event target on given event type. When that event fires, value
 * passed as a first argument to registered function will be emitted by output Observable.
 * When Observable is unsubscribed, function will be unregistered from event target.
```

so this should be fixed by using adding .share() operators to https://github.com/feathersjs-ecosystem/feathers-reactive/blob/master/src/index.js#L34-L37

**Closed** 2018-07-24 02:38 UTC
